input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(40, 43, 47)
    check_color= rgb(73, 74, 76)
    fail_color= rgb(92, 56, 56)

    font_color = rgb(40, 43, 47)
    fade_on_empty = false
    rounding = 1

    position = 0, -20
    halign = center
    valign = center
}

background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2
}
