-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.95,
        inactive_opacity = 0.9,
        rounding = 0,
        shadow = {
            range = 20,
        },
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(393c41ff)", "rgba(8a8784ff)"},
                angle = 45,
            },
        },
        gaps_in = 5,
        gaps_out = 10,
    },
})
